DROP VIEW IF EXISTS PROJECT_COUNT_VIEW;

CREATE VIEW IF NOT EXISTS PROJECT_COUNT_VIEW AS
SELECT CLIENT_ID, COUNT(CLIENT_ID) AS PROJECT_COUNT
FROM PROJECT GROUP BY CLIENT_ID;

SELECT client.NAME, PROJECT_COUNT FROM PROJECT_COUNT_VIEW
INNER JOIN client ON CLIENT_ID = client.ID
WHERE PROJECT_COUNT = (SELECT MAX(PROJECT_COUNT) FROM PROJECT_COUNT_VIEW);
DROP VIEW IF EXISTS PROJECT_COUNT_VIEW;

