DROP TABLE IF EXISTS MIN_MAX_AGE;
CREATE TABLE MIN_MAX_AGE AS
    SELECT NAME, BIRTHDAY FROM WORKER
WHERE BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM WORKER)
OR BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM WORKER);

ALTER TABLE MIN_MAX_AGE ADD COLUMN TYPE VARCHAR(8) BEFORE NAME;
UPDATE MIN_MAX_AGE SET TYPE = 'YOUNGEST' WHERE BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM WORKER);
UPDATE MIN_MAX_AGE SET TYPE = 'ELDEST' WHERE BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM WORKER);
SELECT * FROM MIN_MAX_AGE ORDER BY BIRTHDAY DESC;

