DROP VIEW IF EXISTS PROJECT_TIME;
CREATE VIEW PROJECT_TIME AS
SELECT ID AS NAME, (YEAR(FINISH_DATE) - YEAR(START_DATE)) * 12
               + MONTH(FINISH_DATE) - MONTH(START_DATE)
    AS MONTH_COUNT FROM PROJECT;

SELECT NAME, MONTH_COUNT FROM PROJECT_TIME
WHERE MONTH_COUNT = (SELECT MAX(MONTH_COUNT) FROM PROJECT_TIME);

DROP VIEW PROJECT_TIME;